name: Build and Push Docker Image

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract Git tag
        id: get_tag
        run: echo "::set-output name=GIT_TAG::$(git describe --tags --abbrev=0 2>/dev/null || echo latest)"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/my-image:${{ steps.get_tag.outputs.GIT_TAG }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/my-image:latest
