name: Deploy to VPS

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no user@your_vps_ip << 'EOF'
            docker pull your_dockerhub_username/my-image:latest
            docker stop my-container || true
            docker rm my-container || true
            docker run -d --name my-container -p 80:80 your_dockerhub_username/my-image:latest
          EOF

# TODO add secret and rename variables
