@MailBuilder_HostAddress = http://192.168.31.214:6543

GET {{MailBuilder_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{MailBuilder_HostAddress}}/api/mailbuilder
Content-Type: application/json
Accept: application/json

{
  "usedMail": "ndrafted638@fanto.addymail.com",
  "toSend": "ihrsdfseantwort@dhl.de"
}