@MailBuilder_HostAddress = http://localhost:5075
# @MailBuilder_HostAddress = http://37.114.58.223:8088
# @MailBuilder_HostAddress = http://localhost:5000

GET {{MailBuilder_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{MailBuilder_HostAddress}}/api/mailbuilder
Content-Type: application/json
Accept: application/json

{
  "usedMail": "dismay.grew947@wasabi.anonaddy.com",
  "toSend": "sicherheit@wunschgutschein.com"
}