@MailBuilder_HostAddress = http://localhost:5075

GET {{MailBuilder_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{MailBuilder_HostAddress}}/api/mailbuilder
Content-Type: application/json
Accept: application/json

{
  "usedMail": "me@fanto.dev",
  "toSend": "roland.john@tertia.de"
}