name: Tagging
on:
  push:
    branches:
      - release

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Get tag
        id: get_tag
        run: echo "$(git describe --tags --abbrev=0)"
